/**
 * Example library bundled for the static demo (no backend).
 *
 * `examples.json` is generated by `server/scripts/dump_examples.py` from the
 * real API, simulations included, so the demo animates exactly what the server
 * would return. The server test suite fails when it is stale.
 */

import type {
  ExampleInfo,
  MechanismDict,
  MechanismResponse,
  SimulationFrame,
} from '../types/mechanism';
import bundle from './examples.json';

interface BundledExample {
  info: ExampleInfo;
  mechanism: MechanismDict;
  is_buildable: boolean;
  rotation_period: number | null;
  simulation: {
    frames: SimulationFrame[];
    joint_names: string[];
    is_complete: boolean;
  };
}

// The JSON module type is structural (tuples widen to arrays); the shape is
// guaranteed by the server test that regenerates the file.
const examples = bundle as unknown as Record<string, BundledExample>;

export function listBundledExamples(): ExampleInfo[] {
  return Object.values(examples).map((example) => example.info);
}

/**
 * Mirror `POST /api/examples/{name}/load` followed by the simulation call:
 * a `MechanismResponse` with a `local-` id (so later simulations go through
 * the client-side path) and the precomputed loci.
 */
export function loadBundledExample(name: string): {
  mechanism: MechanismResponse;
  frames: SimulationFrame[];
  jointNames: string[];
} {
  const example = examples[name];
  if (!example) {
    throw new Error(`Example '${name}' is not bundled`);
  }
  const now = new Date().toISOString();
  return {
    mechanism: {
      ...example.mechanism,
      id: `local-example-${name}`,
      created_at: now,
      updated_at: now,
      is_buildable: example.is_buildable,
      rotation_period: example.rotation_period,
      error: null,
    },
    frames: example.simulation.frames,
    jointNames: example.simulation.joint_names,
  };
}
